apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: keycloak
      version: 15.0.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  targetNamespace: kube-utils
  install:
    createNamespace: true
  values:
    auth:
      adminUser: admin
    postgresql:
      persistence:
        enabled: true
        size: 8Gi
    service:
      type: NodePort
    resources:
      limits:
        memory: 1Gi
        cpu: 1000m
