apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: sealed-secrets
      version: '>=1.15.0-0'
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
  targetNamespace: kube-utils
  install:
    createNamespace: true
  values:
    fullnameOverride: sealed-secrets-controller
