apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: nginx
      version: '15.14.0'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  targetNamespace: demo-app
  install:
    createNamespace: true
  values:
    service:
      type: NodePort
      nodePorts:
        http: 30080
